# Generated by Django 4.1.13 on 2024-04-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='id',
        ),
        migrations.AddField(
            model_name='posts',
            name='post_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='posts',
            index=models.Index(fields=['user_id'], name='posts_posts_user_id_fd2973_idx'),
        ),
        migrations.AddIndex(
            model_name='posts',
            index=models.Index(fields=['post_id'], name='posts_posts_post_id_ae9781_idx'),
        ),
    ]
