# Generated by Django 4.2.11 on 2024-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_mediaofposts_media_alter_posts_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaofposts',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
