# Generated by Django 4.2.11 on 2024-04-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('posts', '0003_postiswatched'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postiswatched',
            unique_together={('post_id', 'user_id')},
        ),
    ]
