# Generated by Django 5.0.2 on 2024-03-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background_url',
            field=models.ImageField(blank=True, upload_to='backgrounds/'),
        ),
    ]
