# Generated by Django 5.0.2 on 2024-03-21 13:58

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_birth_date'),
    ]

    operations = [
    ]
