"""
Django settings for social_network project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import environ
import os

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(BASE_DIR /'.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tq@z^zzy63%i6(+)=4l6vr2-g2p^#ba6&*-$u3b)d(bjb&(evb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
INTERNAL_IPS = [
    '127.0.0.1',
]

# Application definition

INSTALLED_APPS = [
    'chat.apps.ChatConfig',
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', # pip install djangorestframework
    'corsheaders', # pip install django-cors-headers
    'django_mongoengine',
    'storages',
    # 'debug_toolbar',
    'homepage',
    'users',
    'posts',
    # 'chat',
    'comments',
    'reactions',
    'friends',
    'userprofiles',
    'channels',
    'navbar',
    'notifications',
]

MIDDLEWARE = [
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'social_network.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'social_network.wsgi.application'

ASGI_APPLICATION = "social_network.asgi.application"

REDIS_HOST = env('REDIS_HOST')
REDIS_PORT = env('REDIS_PORT')
REDIS_PASSWORD = env('REDIS_PASSWORD')

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    },
    "redis": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
    "redis": {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
}

try:
    from django_redis import get_redis_connection
    redis_conn = get_redis_connection("redis")
    redis_conn.ping()
    print("Connected to Redis")
except Exception as e:
    print(f"Not connected to Redis: {e}")

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    #kết nối tới relica postgres 
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env('POSTGRES_DB'),
        'USER': env('POSTGRES_USER'),
        'PASSWORD': env('POSTGRES_PASSWORD'),
        'HOST': env('POSTGRES_HOST'),
        'PORT': env('POSTGRES_PORT'),
    },
}

MONGODB_DATABASES = {
    "default": {
        "name": env('MONGODB_NAME'),
        "host": env('MONGODB_HOST'),
    }
}

import mongoengine
from pymongo import ReadPreference

mongoengine.connect(
    db=env('MONGODB_NAME'),
    host=env('MONGODB_HOST'),
)

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH_USER_MODEL = 'users.User'

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True 

# logging setting
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
        "mytype": {
            "format": "{asctime}:{levelname} - {name} {module}.py (line {lineno:d}). {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "class": "logging.FileHandler",
            "filename": env('DJANGO_LOG_FILE'),
            "level": env('DJANGO_LOG_LEVEL'),
            "formatter": "mytype",
        },
        'logtail': {
            'class': 'logtail.LogtailHandler',
            'source_token': env('BETTERSTACK_SOURCE_TOKEN'),
        },
        # "console": {
        #     "class": "logging.StreamHandler",
        #     "level": "DEBUG",
        #     "formatter": "mytype",
        # }
    },
    "loggers": {
        "users.views": {
            "handlers": ["logtail", "file"],
            "level": env('DJANGO_LOG_LEVEL'),
            "propagate": False,
        },
        "userprofiles.views": {
            "handlers": ["logtail", "file"],
            "level": env('DJANGO_LOG_LEVEL'),
            "propagate": False,
        },
        "userprofiles.viewsEdit": {
            "handlers": ["logtail", "file"],
            "level": env('DJANGO_LOG_LEVEL'),
            "propagate": False,
        },
        "reactions.views": {
            "handlers": ["logtail", "file"],
            "level": env('DJANGO_LOG_LEVEL'),
            "propagate": False,
        },
        "notifications.views": {
            "handlers": ["logtail", "file"],
            "level": env('DJANGO_LOG_LEVEL'),
            "propagate": False,
        },
        "navbar.views": {
            "handlers": ["logtail", "file"],
            "level": env('DJANGO_LOG_LEVEL'),
            "propagate": False,
        },
        "homepage.views": {
            "handlers": ["logtail", "file"],
            "level": env('DJANGO_LOG_LEVEL'),
            "propagate": False,
        },
        "friends.views": {
            "handlers": ["logtail", "file"],
            "level": env('DJANGO_LOG_LEVEL'),
            "propagate": False,
        },
        "comments.views": {
            "handlers": ["logtail", "file"],
            "level": env('DJANGO_LOG_LEVEL'),
            "propagate": False,
        },
        "chat.views": {
            "handlers": ["logtail", "file"],
            "level": env('DJANGO_LOG_LEVEL'),
            "propagate": False,
        },
        "posts.views": {
            "handlers": ["logtail", "file"],
            "level": env('DJANGO_LOG_LEVEL'),
            "propagate": False,
        },
        "users.models": {
            "handlers": ["logtail", "file"],
            "level": env('DJANGO_LOG_LEVEL'),
            "propagate": False,
        },
    },
}

# AWS configuration

AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')


# Basic Storage configuration for Amazon S3 (Irrespective of Django versions)

AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME') # - Enter your S3 bucket name HERE

AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

AWS_S3_FILE_OVERWRITE = False


# Django < 4.2

'''

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

'''

# Django 4.2 >

STORAGES = {

    # Media file (image) management   
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
    },
    
    # CSS and JS file management
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
    },
}


# Add STATIC_URL setting
STATIC_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/static/"
MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/media/"