# Generated by Django 3.2.10 on 2024-04-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name_plural': 'Conversation'},
        ),
    ]
