# Generated by Django 3.2.10 on 2024-04-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversation_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='conversation_title',
            new_name='title',
        ),
    ]
