# Generated by Django 5.0.2 on 2024-03-31 13:03

import userprofiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='users/default/avatar_default.png', upload_to=userprofiles.models.media_directory_path)),
                ('background', models.ImageField(blank=True, default='users/default/background_default.jpg', upload_to=userprofiles.models.media_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('work', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
