# Generated by Django 4.1.13 on 2024-04-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprofile',
            name='_destroy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_destroy',
            field=models.BooleanField(default=False),
        ),
    ]
