# Generated by Django 4.2.11 on 2024-04-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_work',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='place_birth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
