# Generated by Django 4.1.13 on 2024-04-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_imageprofile__destroy_userprofile__destroy'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='imageprofile',
            index=models.Index(fields=['user_id'], name='userprofile_user_id_03ed93_idx'),
        ),
        migrations.AddIndex(
            model_name='linkprofile',
            index=models.Index(fields=['user_id'], name='userprofile_user_id_011e75_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user_id'], name='userprofile_user_id_e911da_idx'),
        ),
    ]
