# Generated by Django 4.2.11 on 2024-04-22 18:43

from django.db import migrations, models
import userprofiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_userprofile_address_work_userprofile_place_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/users/default/avatar_default.png', upload_to=userprofiles.models.media_directory_path),
        ),
        migrations.AlterField(
            model_name='imageprofile',
            name='background',
            field=models.ImageField(blank=True, default='media/users/default/background_default.jpg', upload_to=userprofiles.models.media_directory_path),
        ),
    ]
